export const welcomeNote = {
  title: "Welcome to Anynote",
  content: [
    "Everything you write here is **end-to-end encrypted** on your device before it's saved. Not even the server can read it.",
    "",
    "## Getting started",
    "",
    "- [ ] Save your Emergency Kit somewhere safe. Without it, a lost password means lost notes.",
    "- [ ] Create a note with the **+** next to Documents, or press ⌘⌥N (Ctrl+Alt+N)",
    "- [ ] Press ⌘K (Ctrl+K) to search notes and run commands",
    "- [ ] Press ? to see every keyboard shortcut",
    "",
    "## Writing",
    "",
    "Notes are plain Markdown. Type `#` for a heading, `-` for a list, `1.` for a numbered list, `[ ]` for a task, `>` for a quote and three backticks for a code block. Select text for **bold**, *italic*, ~~strikethrough~~, `code` and links.",
    "",
    "> Right-click anywhere in a note to turn blocks into something else or insert tables, images and dividers.",
    "",
    "```js",
    'console.log("Code blocks are highlighted for most languages");',
    "```",
    "",
    "| Tables | can be | resized |",
    "| --- | --- | --- |",
    "| Drag a column edge | to resize it | Hover the edges for + |",
    "",
    "- **Images:** paste, drag in or insert them. They're encrypted too. Click one to zoom, drag its edge to resize and add a caption from its toolbar.",
    "- **Links between notes:** type `[[` to link another note. Linked notes list their backlinks at the bottom.",
    "- **Bookmarks:** put a link on its own line, click into it and choose *Show as bookmark* to turn it into a card like this:",
    "",
    '<!-- anynote:bookmark {"description":"End-to-end encrypted, minimal notes.","siteName":"GitHub"} -->',
    "",
    "[Anynote on GitHub](https://github.com/aelpxy/anynote)",
    "",
    "## Organizing",
    "",
    "- Group notes into folders, and drag notes and folders to reorder or move them",
    "- ⌘-click (Ctrl-click) or Shift-click to select several notes at once",
    "- Press F2 or right-click to rename, duplicate, add to favorites or move to trash. Click the icon above a note's title to change it",
    "- Deleted notes stay in the trash for 30 days",
    "- Find text in a note with ⌘F (Ctrl+F) and across all notes with ⌘⇧F (Ctrl+Shift+F)",
    "",
    "## Making it yours",
    "",
    "- Switch between light and dark themes, and pick a font, text size and line spacing for your notes",
    "- Hide the sidebar with ⌘\\ (Ctrl+\\) or enter focus mode with ⌘. (Ctrl+.)",
    "- Long notes get an outline for jumping between headings. Note info and export to Markdown or PDF are at the top of every note",
    "- Install Anynote as an app from your browser's menu, or Add to Home Screen on a phone",
    "",
    "Changes save as you type, even on a flaky connection. ⌘S (Ctrl+S) saves right away.",
  ].join("\n"),
  isFavorite: true,
};
